- hosts: aws
  gather_facts: False
  connection: local
  tasks:
    - name: check kinesis video stream
      command: aws kinesisvideo list-streams --region {{region}}
      changed_when: False
      register: list_streams_rsp

    - name: parse response and check if video stream is there
      set_fact:
        streams: "{{list_streams_rsp.stdout | from_json | json_query('StreamInfoList') | map(attribute='StreamName') | list}}"

    - name: create kinesis video stream
      command: aws kinesisvideo create-stream --stream-name {{videoStreamName}} --data-retention-in-hours 24 --region {{region}}
      when: "projectName not in streams"

    - name: create CF stack
      cloudformation:
        stack_name: "{{projectName}}"
        state: present
        region: "{{region}}"
        template: files/cloudformation-hardhat-detector.yml
        template_parameters:
            AppName: "{{projectName}}"
            StreamNames: "{{videoStreamName}}"
            TagFilters: '{"key": "face"}, {"key": "hardhat"}, {"key": "helmet"}'
            SageMakerEndpoint: "{{projectName}}"
            LambdaFunctionName: "{{lambdaName}}"
            VpcId: "{{vpcId}}"
            PublicSubnets: "{{publicSubnets}}"
        tags:
          Project: hardhat-detector-POC
