AWSTemplateFormatVersion: "2010-09-09"
Description: "create hardhat-detector resources"
Parameters:
  DBName:
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
    Default: wordpressdb
    Description: The WordPress database name
    MaxLength: "64"
    MinLength: "1"
    Type: String
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HardHatDetectorRole
      Description: "IAM Role allow rekognition to have access to kinesis video stream and data stream"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rekognition.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: rekognitionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - kinesisvideo:GetDataEndpoint
                  - kinesisvideo:GetMedia
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - rekognition:*
                Resource:
                  - "*"
      Tags:
        - Key: Project
          Value: hardhat-detector-POC

  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: hardhat-detector-POC
      RetentionPeriodHours: 24
      ShardCount: 1
      Tags:
        - Key: Project
          Value: hardhat-detector-POC

Outputs:
  IAMRoleArn:
    Value: !GetAtt IAMRole.Arn
